# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 398)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, -10, 209, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(220, 0, 351, 301))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.streetEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.streetEdit.setObjectName("streetEdit")
        self.gridLayout_2.addWidget(self.streetEdit, 4, 0, 1, 1)
        self.zipCodeEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.zipCodeEdit.setObjectName("zipCodeEdit")
        self.gridLayout_2.addWidget(self.zipCodeEdit, 4, 1, 1, 1)
        self.cityEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.cityEdit.setObjectName("cityEdit")
        self.gridLayout_2.addWidget(self.cityEdit, 4, 2, 1, 1)
        self.peselEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.peselEdit.setObjectName("peselEdit")
        self.gridLayout_2.addWidget(self.peselEdit, 3, 0, 1, 3)
        self.birthDateEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.birthDateEdit.setObjectName("birthDateEdit")
        self.gridLayout_2.addWidget(self.birthDateEdit, 2, 0, 1, 3)
        self.lastNameEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.gridLayout_2.addWidget(self.lastNameEdit, 1, 0, 1, 3)
        self.nameEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_2.addWidget(self.nameEdit, 0, 0, 1, 3)
        self.saveButton = QtWidgets.QPushButton(parent=Dialog)
        self.saveButton.setGeometry(QtCore.QRect(0, 310, 561, 32))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Pesel"))
        self.label.setText(_translate("Dialog", "Imie:"))
        self.label_4.setText(_translate("Dialog", "Data Urodzenia"))
        self.label_2.setText(_translate("Dialog", "Adres (ulica/kodpocztowy/miasto)"))
        self.label_5.setText(_translate("Dialog", "Nazwisko:"))
        self.saveButton.setText(_translate("Dialog", "Wyslij"))
